-- Sample products for local testing/demo purposes.
insert into public.products (slug, title, description, short_description, price, compare_at_price, category, tags, image_url, stock_quantity, status)
values
  ('wireless-headphones', 'Wireless Headphones', 'Over-ear wireless headphones with active noise cancellation and 30-hour battery life.', 'Noise-cancelling wireless headphones', 4999.00, 5999.00, 'Electronics', array['audio', 'wireless'], 'https://picsum.photos/seed/wireless-headphones/600/600', 25, 'active'),
  ('smart-watch', 'Smart Watch', 'Fitness-tracking smart watch with heart-rate monitor, GPS, and week-long battery.', 'Feature-packed fitness smart watch', 6999.00, null, 'Electronics', array['wearable', 'fitness'], 'https://picsum.photos/seed/smart-watch/600/600', 15, 'active'),
  ('bluetooth-speaker', 'Portable Bluetooth Speaker', 'Compact waterproof speaker with rich bass and 12-hour playtime.', 'Waterproof portable speaker', 2499.00, 2999.00, 'Electronics', array['audio', 'portable'], 'https://picsum.photos/seed/bluetooth-speaker/600/600', 40, 'active'),
  ('cotton-tshirt', 'Classic Cotton T-Shirt', 'Soft, breathable 100% cotton t-shirt available in multiple colors.', 'Everyday cotton t-shirt', 799.00, null, 'Apparel', array['casual', 'cotton'], 'https://picsum.photos/seed/cotton-tshirt/600/600', 100, 'active'),
  ('denim-jacket', 'Denim Jacket', 'Classic fit denim jacket with a timeless look, built to last.', 'Timeless classic-fit denim jacket', 2999.00, 3499.00, 'Apparel', array['outerwear', 'denim'], 'https://picsum.photos/seed/denim-jacket/600/600', 30, 'active'),
  ('running-shoes', 'Running Shoes', 'Lightweight running shoes with responsive cushioning for everyday training.', 'Lightweight cushioned running shoes', 3499.00, null, 'Apparel', array['footwear', 'sport'], 'https://picsum.photos/seed/running-shoes/600/600', 50, 'active'),
  ('ceramic-mug-set', 'Ceramic Mug Set (4-Pack)', 'Set of four handcrafted ceramic mugs, dishwasher and microwave safe.', 'Handcrafted 4-piece mug set', 1299.00, 1599.00, 'Home & Living', array['kitchen', 'ceramic'], 'https://picsum.photos/seed/ceramic-mug-set/600/600', 60, 'active'),
  ('scented-candle', 'Scented Soy Candle', 'Long-burning soy wax candle with a calming lavender fragrance.', 'Calming lavender soy candle', 599.00, null, 'Home & Living', array['candle', 'home'], 'https://picsum.photos/seed/scented-candle/600/600', 80, 'active'),
  ('throw-blanket', 'Cozy Throw Blanket', 'Ultra-soft knitted throw blanket, perfect for cooler evenings.', 'Soft knitted throw blanket', 1899.00, 2199.00, 'Home & Living', array['textile', 'home'], 'https://picsum.photos/seed/throw-blanket/600/600', 35, 'active'),
  ('leather-wallet', 'Leather Bifold Wallet', 'Genuine leather bifold wallet with RFID-blocking card slots.', 'RFID-blocking leather wallet', 1499.00, null, 'Accessories', array['leather', 'wallet'], 'https://picsum.photos/seed/leather-wallet/600/600', 45, 'active'),
  ('sunglasses', 'Polarized Sunglasses', 'UV-protective polarized sunglasses with a durable lightweight frame.', 'UV-protective polarized sunglasses', 1799.00, 2199.00, 'Accessories', array['eyewear', 'summer'], 'https://picsum.photos/seed/sunglasses/600/600', 20, 'active'),
  ('canvas-backpack', 'Canvas Backpack', 'Durable canvas backpack with padded laptop sleeve and multiple pockets.', 'Durable everyday canvas backpack', 2199.00, null, 'Accessories', array['bag', 'travel'], 'https://picsum.photos/seed/canvas-backpack/600/600', 28, 'active')
on conflict (slug) do nothing;
